### ISSUE TITLE
Show who proposed the afk status

### ISSUE THREAD

**Issue by photm5** [froozen/pybot-plugins#2]
I added `afk.%s.proposer` in #1 in order to use it in the )status message, but totally forgot about that later on. I would open a PR for that, but I‘m unsure about the format that should be used. A few proposals:
1. `proposed as afk by %s`
2. `probably afk: %s`
3. `probably afk (%s)`
4. `probably afk (by %s)`

**Comment by froozen** [comment]
I believe, that the first option is the best. It's the most explicit one and explains the situation properly.
